// <auto-generated />
namespace BookHotel.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class RoomlayerChanged : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RoomlayerChanged));
        
        string IMigrationMetadata.Id
        {
            get { return "202009061333044_Room#layerChanged"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
